# Generated by Django 6.0 on 2025-12-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='user_role_user_id_d8192c_idx',
            old_name='accounts_us_user_id_d06a5b_idx',
        ),
        migrations.RenameIndex(
            model_name='userrole',
            new_name='user_role_role_id_8c260c_idx',
            old_name='accounts_us_role_id_3b7362_idx',
        ),
        migrations.AlterModelTable(
            name='role',
            table='role',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='user_role',
        ),
    ]
