# Generated by Codex to fix a previously edited migration (adds missing DB column).

from django.db import migrations


def add_updated_at_column_if_missing(apps, schema_editor):
    table_name = "user"
    column_name = "updated_at"

    with schema_editor.connection.cursor() as cursor:
        columns = [
            c.name
            for c in schema_editor.connection.introspection.get_table_description(cursor, table_name)
        ]

    if column_name in columns:
        return

    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            f"ALTER TABLE `{table_name}` "
            f"ADD COLUMN `{column_name}` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)"
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_options_and_more"),
    ]

    operations = [
        migrations.RunPython(add_updated_at_column_if_missing, migrations.RunPython.noop),
    ]
