# Generated by Django 6.0 on 2025-12-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='maintenance',
            new_name='maintenance_equipme_ced51c_idx',
            old_name='maintenance_equipment_4fb533_idx',
        ),
        migrations.RenameIndex(
            model_name='maintenance',
            new_name='maintenance_status_bfb454_idx',
            old_name='maintenance_status_a7d250_idx',
        ),
        migrations.AlterModelTable(
            name='maintenance',
            table='maintenance',
        ),
    ]
