# Generated by Django 6.0 on 2025-12-15 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktxn'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='consumable',
            new_name='consumable_code_976d6a_idx',
            old_name='inventory_c_code_1718ae_idx',
        ),
        migrations.RenameIndex(
            model_name='consumable',
            new_name='consumable_current_ee3ff0_idx',
            old_name='inventory_c_current_54a304_idx',
        ),
        migrations.RenameIndex(
            model_name='equipment',
            new_name='equipment_categor_fc71b2_idx',
            old_name='inventory_e_categor_9b2228_idx',
        ),
        migrations.RenameIndex(
            model_name='equipment',
            new_name='equipment_status_92035a_idx',
            old_name='inventory_e_status_6804f8_idx',
        ),
        migrations.RenameIndex(
            model_name='equipmentstatuslog',
            new_name='equipment_s_equipme_8b2a16_idx',
            old_name='inventory_e_equipme_745b88_idx',
        ),
        migrations.RenameIndex(
            model_name='stocktxn',
            new_name='stock_txn_consuma_afbf00_idx',
            old_name='inventory_s_consuma_c289c1_idx',
        ),
        migrations.AddField(
            model_name='equipmentstatuslog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='consumable',
            table='consumable',
        ),
        migrations.AlterModelTable(
            name='equipment',
            table='equipment',
        ),
        migrations.AlterModelTable(
            name='equipmentcategory',
            table='equipment_category',
        ),
        migrations.AlterModelTable(
            name='equipmentstatuslog',
            table='equipment_status_log',
        ),
        migrations.AlterModelTable(
            name='stocktxn',
            table='stock_txn',
        ),
    ]
