# Generated by Django 6.0 on 2025-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_inventory_c_code_1718ae_idx_consumable_code_976d6a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BORROWED', 'Borrowed'), ('OUT', 'Out (Legacy)'), ('RETURN_PENDING', 'Return Pending'), ('MAINTENANCE', 'Maintenance'), ('DISCARDED', 'Discarded')], default='AVAILABLE', max_length=32),
        ),
        migrations.AlterField(
            model_name='equipmentstatuslog',
            name='from_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BORROWED', 'Borrowed'), ('OUT', 'Out (Legacy)'), ('RETURN_PENDING', 'Return Pending'), ('MAINTENANCE', 'Maintenance'), ('DISCARDED', 'Discarded')], max_length=32),
        ),
        migrations.AlterField(
            model_name='equipmentstatuslog',
            name='to_status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('BORROWED', 'Borrowed'), ('OUT', 'Out (Legacy)'), ('RETURN_PENDING', 'Return Pending'), ('MAINTENANCE', 'Maintenance'), ('DISCARDED', 'Discarded')], max_length=32),
        ),
    ]
