# Generated by Django 6.0 on 2025-12-15 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0003_alter_borrowrequest_status'),
        ('inventory', '0004_alter_equipment_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktxn',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_stock_txns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stocktxn',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=16),
        ),
        migrations.AlterField(
            model_name='stocktxn',
            name='type',
            field=models.CharField(choices=[('IN', 'In'), ('OUT', 'Out')], max_length=16),
        ),
        migrations.AddIndex(
            model_name='stocktxn',
            index=models.Index(fields=['status'], name='stock_txn_status_174fe1_idx'),
        ),
    ]
