# Generated by Django 6.0 on 2025-12-15 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='borrowitem',
            new_name='borrow_item_request_e03553_idx',
            old_name='borrowing_b_request_3f68b4_idx',
        ),
        migrations.RenameIndex(
            model_name='borrowrequest',
            new_name='borrow_requ_applica_fcb4ab_idx',
            old_name='borrowing_b_applica_036766_idx',
        ),
        migrations.AlterModelTable(
            name='borrowapproval',
            table='borrow_approval',
        ),
        migrations.AlterModelTable(
            name='borrowitem',
            table='borrow_item',
        ),
        migrations.AlterModelTable(
            name='borrowrequest',
            table='borrow_request',
        ),
        migrations.AlterModelTable(
            name='returnrecord',
            table='return_record',
        ),
    ]
