# Generated by Django 6.0 on 2025-12-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrowing', '0002_rename_borrowing_b_request_3f68b4_idx_borrow_item_request_e03553_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('OUT', 'Out'), ('CLOSED', 'Closed')], default='REQUESTED', max_length=20),
        ),
    ]
